spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cboard?useUnicode=true&useSSL=false&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
    name: CBoard Meta Data
    druid:
      validation-query: SELECT 1
