spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/H2Data/cboard;AUTO_SERVER=TRUE;LOG=0;UNDO_LOG=0
    username: sa
    password:
    name: cboard
    druid:
      validation-query: select 1