server:
  port: 8888
  servlet:
    context-path: /cboard
spring:
  datasource:
    schema: classpath:h2-demo/h2.sql
    data: classpath:h2-demo/sample_data.sql
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/H2Data/cboard;AUTO_SERVER=TRUE;LOG=0;UNDO_LOG=0
    username: sa
    password:
    name: cboard
    druid:
      validation-query: select 1
  h2:
    console:
      enabled: true
      path: /h2
  freemarker:
    cache: false
    charset: UTF-8
    suffix: .ftl
    content-type: text/html
    template-loader-path: classpath:/templates/config/
  profiles:
    active: demo
admin_user_id: 1